In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
df = pd.read_csv('/home/lucas/representation-fusion/fusion_metrics2.csv')
df.columns

Index(['tipo_encoder', 'dataset_train', 'dataset_encoder', 'dataset_test',
       'batch', 'tecnica_fusao', 'precision', 'precision_std', 'accuracy',
       'accuracy_std'],
      dtype='object')

In [4]:
df = df.loc[df['tecnica_fusao'] != "mean_individual_models"]

## Análises

## Resultados com as Fusões

Diferenças entre esses testes e o do PIBIC de 2025:

- Os modelos sendo usados seguem a mesma base estrutural (em questão de camadas) do PIBIC passado, são os 10 modelos gerados, entretanto o vetor latente deles foi diminuido para se testar com o VAE.
- Vetores latentes antes: 256 - 2048
- Vetores latentes agora: 256 - 512

Melhores resultados:

In [5]:
df.sort_values(by='accuracy', ascending=False)

,tipo_encoder,dataset_train,dataset_encoder,dataset_test,batch,tecnica_fusao,precision,precision_std,accuracy,accuracy_std
15751,SkipEncoder,PUC,PKLot,PUC,512,mult,0.995709,0.0,0.995707,0.0
15823,SkipEncoder,PUC,PKLot,PUC,1024,mult,0.994885,0.0,0.994883,0.0
15749,SkipEncoder,PUC,PKLot,PUC,512,mean_probs,0.994571,0.0,0.994571,0.0
15748,SkipEncoder,PUC,PKLot,PUC,512,sum,0.994571,0.0,0.994571,0.0
15750,SkipEncoder,PUC,PKLot,PUC,512,max,0.994440,0.0,0.994441,0.0
...,...,...,...,...,...,...,...,...,...,...
35699,SkipEncoder,camera2,PKLot,UFPR04,64,mean_probs,0.333881,0.0,0.394623,0.0
35701,SkipEncoder,camera2,PKLot,UFPR04,64,mult,0.343597,0.0,0.391737,0.0
18060,VariationalEncoder,camera2,CNR,UFPR04,64,max,0.267410,0.0,0.368801,0.0
18061,VariationalEncoder,camera2,CNR,UFPR04,64,mult,0.292098,0.0,0.351083,0.0
18132,VariationalEncoder,camera2,CNR,UFPR04,128,max,0.249602,0.0,0.279227,0.0

Melhores com o menor batch:

In [6]:
df[df['batch'] == 64].sort_values(by='accuracy', ascending=False)

,tipo_encoder,dataset_train,dataset_encoder,dataset_test,batch,tecnica_fusao,precision,precision_std,accuracy,accuracy_std
8647,SkipEncoder,camera1,CNR,camera2,64,mult,0.971662,0.0,0.971655,0.0
34926,SkipEncoder,camera1,PKLot,camera2,64,max,0.971892,0.0,0.971655,0.0
8646,SkipEncoder,camera1,CNR,camera2,64,max,0.970521,0.0,0.970522,0.0
8645,SkipEncoder,camera1,CNR,camera2,64,mean_probs,0.970521,0.0,0.970522,0.0
8644,SkipEncoder,camera1,CNR,camera2,64,sum,0.970521,0.0,0.970522,0.0
...,...,...,...,...,...,...,...,...,...,...
35699,SkipEncoder,camera2,PKLot,UFPR04,64,mean_probs,0.333881,0.0,0.394623,0.0
35698,SkipEncoder,camera2,PKLot,UFPR04,64,sum,0.333881,0.0,0.394623,0.0
35701,SkipEncoder,camera2,PKLot,UFPR04,64,mult,0.343597,0.0,0.391737,0.0
18060,VariationalEncoder,camera2,CNR,UFPR04,64,max,0.267410,0.0,0.368801,0.0
18061,VariationalEncoder,camera2,CNR,UFPR04,64,mult,0.292098,0.0,0.351083,0.0

Melhores em treino/teste diferentes

In [7]:
df[df['dataset_train'] != df['dataset_test']].sort_values(by='accuracy', ascending=False)

,tipo_encoder,dataset_train,dataset_encoder,dataset_test,batch,tecnica_fusao,precision,precision_std,accuracy,accuracy_std
35142,SkipEncoder,camera1,PKLot,camera2,512,max,0.986593,0.0,0.986395,0.0
15052,SkipEncoder,camera9,PKLot,camera2,1024,sum,0.985268,0.0,0.985261,0.0
15053,SkipEncoder,camera9,PKLot,camera2,1024,mean_probs,0.985268,0.0,0.985261,0.0
10661,SkipEncoder,camera3,PKLot,camera2,512,mean_probs,0.984427,0.0,0.984127,0.0
10660,SkipEncoder,camera3,PKLot,camera2,512,sum,0.984427,0.0,0.984127,0.0
...,...,...,...,...,...,...,...,...,...,...
35698,SkipEncoder,camera2,PKLot,UFPR04,64,sum,0.333881,0.0,0.394623,0.0
35701,SkipEncoder,camera2,PKLot,UFPR04,64,mult,0.343597,0.0,0.391737,0.0
18060,VariationalEncoder,camera2,CNR,UFPR04,64,max,0.267410,0.0,0.368801,0.0
18061,VariationalEncoder,camera2,CNR,UFPR04,64,mult,0.292098,0.0,0.351083,0.0
18132,VariationalEncoder,camera2,CNR,UFPR04,128,max,0.249602,0.0,0.279227,0.0

Melhores em domínio diferentes:

In [8]:
cnr = ['camera1', 'camera2', 'camera3', 'camera4', 'camera5', 'camera6', 'camera7', 'camera8', 'camera9']
pklot = ['UFPR04', 'UFPR05', 'PUC']

In [9]:
df[
    ((df['dataset_train'].isin(cnr)) & (df['dataset_test'].isin(pklot)))
      | 
    ((df['dataset_train'].isin(pklot)) & (df['dataset_test'].isin(cnr)))
    ].sort_values(by='accuracy', ascending=False)

,tipo_encoder,dataset_train,dataset_encoder,dataset_test,batch,tecnica_fusao,precision,precision_std,accuracy,accuracy_std
15101,SkipEncoder,camera9,PKLot,PUC,1024,mean_probs,0.978568,0.0,0.978317,0.0
15100,SkipEncoder,camera9,PKLot,PUC,1024,sum,0.978568,0.0,0.978317,0.0
11504,SkipEncoder,camera4,PKLot,PUC,1024,vote,0.976983,0.0,0.976692,0.0
11500,SkipEncoder,camera4,PKLot,PUC,1024,sum,0.977155,0.0,0.976689,0.0
11501,SkipEncoder,camera4,PKLot,PUC,1024,mean_probs,0.977155,0.0,0.976689,0.0
...,...,...,...,...,...,...,...,...,...,...
35699,SkipEncoder,camera2,PKLot,UFPR04,64,mean_probs,0.333881,0.0,0.394623,0.0
35701,SkipEncoder,camera2,PKLot,UFPR04,64,mult,0.343597,0.0,0.391737,0.0
18060,VariationalEncoder,camera2,CNR,UFPR04,64,max,0.267410,0.0,0.368801,0.0
18061,VariationalEncoder,camera2,CNR,UFPR04,64,mult,0.292098,0.0,0.351083,0.0
18132,VariationalEncoder,camera2,CNR,UFPR04,128,max,0.249602,0.0,0.279227,0.0

Melhores de cada um dos modelos

In [10]:
df.sort_values('accuracy', ascending=False).groupby('tipo_encoder').head(3)

,tipo_encoder,dataset_train,dataset_encoder,dataset_test,batch,tecnica_fusao,precision,precision_std,accuracy,accuracy_std
15751,SkipEncoder,PUC,PKLot,PUC,512,mult,0.995709,0.0,0.995707,0.0
15823,SkipEncoder,PUC,PKLot,PUC,1024,mult,0.994885,0.0,0.994883,0.0
15749,SkipEncoder,PUC,PKLot,PUC,512,mean_probs,0.994571,0.0,0.994571,0.0
6822,Encoder,PUC,CNR,PUC,1024,max,0.986225,0.0,0.986220,0.0
7182,Encoder,PUC,PKLot,PUC,1024,max,0.985949,0.0,0.985942,0.0
6823,Encoder,PUC,CNR,PUC,1024,mult,0.985215,0.0,0.985159,0.0
17502,VariationalEncoder,camera1,CNR,camera2,512,max,0.981880,0.0,0.981859,0.0
24461,VariationalEncoder,PUC,PKLot,PUC,1024,mean_probs,0.978666,0.0,0.978667,0.0
24460,VariationalEncoder,PUC,PKLot,PUC,1024,sum,0.978666,0.0,0.978667,0.0

Reproduzindo tabelas do relatório final (PIBIC 2025 - 2026):

1. Autoencoder PKLot, classificadores CNR (cam1 - cam9), batch de 1024, média cross-domain (CNR X PKLot) baseado na técnica

In [11]:
filtro_tabela1 = (
    (df['batch'] == 1024) &
    (df['dataset_test'].isin(pklot)) &
    (df['dataset_encoder'] == 'PKLot') &
    (df['dataset_train'].isin(cnr))
)

agg_tabela1 = (
    df.loc[filtro_tabela1]
      .groupby(['tipo_encoder', 'tecnica_fusao', 'dataset_train'])['accuracy']
      .mean()
      .sort_values(ascending=False)
      .rename('acc_mean')
      .reset_index()
)

agg_tabela1

           tipo_encoder tecnica_fusao dataset_train  acc_mean
0           SkipEncoder    mean_probs       camera9  0.897629
1           SkipEncoder           sum       camera9  0.897629
2           SkipEncoder          mult       camera9  0.893480
3           SkipEncoder          vote       camera9  0.893407
4           SkipEncoder          vote       camera5  0.886217
..                  ...           ...           ...       ...
130             Encoder           max       camera1  0.692943
131  VariationalEncoder           max       camera3  0.685649
132             Encoder          mult       camera2  0.678910
133             Encoder           max       camera3  0.667923
134             Encoder           max       camera2  0.663489

[135 rows x 4 columns]

2. Autoencoder CNR, classificadores PKLot, batch de 1024, média cross-domain (PKLot x CNR) baseado na técnica

In [12]:
filtro_tabela2 = (
    (df['batch'] == 1024) &
    (df['dataset_test'].isin(cnr)) &
    (df['dataset_encoder'] == 'CNR') &
    (df['dataset_train'].isin(pklot))
)

agg_tabela2 = (
    df.loc[filtro_tabela2]
      .groupby(['tipo_encoder', 'tecnica_fusao', 'dataset_train'])['accuracy']
      .mean()
      .sort_values(ascending=False)
      .rename('acc_mean')
      .reset_index()
)

agg_tabela2

          tipo_encoder tecnica_fusao dataset_train  acc_mean
0          SkipEncoder    mean_probs           PUC  0.897581
1          SkipEncoder           sum           PUC  0.897581
2          SkipEncoder          vote           PUC  0.896783
3          SkipEncoder          mult           PUC  0.886143
4   VariationalEncoder           sum           PUC  0.868719
5   VariationalEncoder    mean_probs           PUC  0.868719
6   VariationalEncoder          vote           PUC  0.868422
7   VariationalEncoder          mult           PUC  0.864926
8          SkipEncoder           max           PUC  0.853359
9   VariationalEncoder           max           PUC  0.846130
10             Encoder           max           PUC  0.811369
11             Encoder          mult           PUC  0.804078
12             Encoder    mean_probs           PUC  0.803010
13             Encoder           sum           PUC  0.803010
14             Encoder          vote           PUC  0.802097
15  VariationalEncoder           max        UFPR05  0.785949
16  VariationalEncoder          mult        UFPR05  0.753884
17  VariationalEncoder          vote        UFPR05  0.745117
18  VariationalEncoder           sum        UFPR05  0.744657
19  VariationalEncoder    mean_probs        UFPR05  0.744657
20             Encoder           max        UFPR05  0.735518
21         SkipEncoder    mean_probs        UFPR04  0.729609
22         SkipEncoder           sum        UFPR04  0.729609
23             Encoder          mult        UFPR05  0.728547
24         SkipEncoder          mult        UFPR04  0.725135
25             Encoder          vote        UFPR05  0.725106
26             Encoder           sum        UFPR05  0.724015
27             Encoder    mean_probs        UFPR05  0.724015
28  VariationalEncoder          vote        UFPR04  0.710616
29  VariationalEncoder           sum        UFPR04  0.709829
30  VariationalEncoder    mean_probs        UFPR04  0.709829
31         SkipEncoder          vote        UFPR04  0.700501
32         SkipEncoder           max        UFPR05  0.698027
33         SkipEncoder           max        UFPR04  0.692612
34         SkipEncoder           sum        UFPR05  0.689900
35         SkipEncoder    mean_probs        UFPR05  0.689900
36         SkipEncoder          mult        UFPR05  0.681349
37         SkipEncoder          vote        UFPR05  0.680448
38  VariationalEncoder          mult        UFPR04  0.675677
39             Encoder           max        UFPR04  0.637732
40             Encoder          mult        UFPR04  0.633009
41             Encoder           sum        UFPR04  0.628964
42             Encoder    mean_probs        UFPR04  0.628964
43             Encoder          vote        UFPR04  0.625814
44  VariationalEncoder           max        UFPR04  0.575223

## Resultados sem as fusões